### ISSUE TITLE
Configure continuous integration

### ISSUE THREAD

**Issue by robinbb** [LeapYear/inline-java#3]
Suggest that we augment the repo with a Dockerfile that uses Nix to build all packages in this repo. We can use Wercker as a CI service.

**Comment by mboes** [comment]
The upstream repo tweag/inline-java has CircleCI already setup. It runs the tests too.

In https://github.com/tweag/inline-java/pull/8, I added a Dockerfile and enabled Wercker support based on it. See here: https://app.wercker.com/tweag/inline-java/runs. I created https://github.com/tweag/stack-docker-nix to factor the common parts of the sparkle and inline-java Dockefiles into a single base image.

Further, I setup triggers so that if you update stack-docker-nix, then the downstream images will be rebuilt.

Reassigning to you for verification.

**Comment by robinbb** [comment]
Verified. Thanks!
